### ISSUE TITLE
Recording Speed problems

### ISSUE THREAD

**Issue by elbadryd** [shaynet10/puppeteer-video-recorder#11]
Hello,
I am trying to use this package to record html animations but it seems that the output mp4 is faster than the actual animation i am capturing? Am i doing something wrong? or is there a way to slow down the speed of capture?
```    
await page.goto('https://webkit.org/blog-files/3d-transforms/morphing-cubes.html');
    await page.waitForSelector('#shape');
    await recorder.start(clipPath);
    setTimeout(async () => {
      console.log('stopping recording');
      await recorder.stop();
      console.log('closing page');
      await page.close();
      console.log('closed page');
    }, 12000);
```
Output: https://user-images.githubusercontent.com/40278300/151414812-027dcbdd-0662-4979-af85-4ab518fd8d75.mp4
Original: https://webkit.org/blog-files/3d-transforms/morphing-cubes.html

**Comment by arash-bizcover** [comment]
Hi @elbadryd 
WHy did you close this? I see the same problem ...
