### ISSUE TITLE
Dependency on old version of puppeteer

### ISSUE THREAD

**Issue by dobesv** [shaynet10/puppeteer-video-recorder#6]
When I add this to my project I get a second copy of puppeteer because this library depends on puppeteer version 5 but now puppeteer version 10 is out.  Any chance the dependency could be changed to be a peer dependency and dev dependency instead of a regular dependency?

**Comment by shaynet10** [comment]
Thanks for noticing my friend.
I think that by mistake I took Puppeteer's installed package from a test I made to the package and added it to the main package.json
So in the new version 1.0.4 it should be fixed.
Please update me if you see this issue again.
And again thanks :)
