### ISSUE TITLE
Impossible to open '{folder}\{folder}\images\1631212191170.jpg'

### ISSUE THREAD

**Issue by incoming-th** [shaynet10/puppeteer-video-recorder#8]
HI

Thanks for this package, I was playing a bit with it and stuck on the video creation.

It seems that when define a path in the recorder.init(page, **folder**) it is also added in the images.txt files.

Sounds legit, but when using **folder** as './logs' then it is failing:

`await recorder.init(page, './logs');`

![image](https://user-images.githubusercontent.com/26375917/132743957-a194303b-aca2-4a5c-b0db-344c30da07b9.png)

The folder is duplicated, and ffmpeg cannot find the image of course.

When removing the {folder} inside the images.txt file, then the video can be generated.

Let me know if that's a bug or if it's something I am doing incorrectly.

**Comment by incoming-th** [comment]
As a workaround, instead of using:

`await recorder.init(page, './logs');`

You can use:

`await recorder.screenshots.stop();`
`await recorder.createVideo('ffmpeg -f concat -safe 0 -i images.txt -framerate 60 logs\filename.webm');`

**Comment by euberdeveloper** [comment]
I noticed that it does not work if the path is relative. You can just use `path.join()` instead #13
